logLevel = "debug" # "debug" | "warn" | "error"
telemetry = false

[install]
optional = true
dev = true
peer = true
auto = "auto"
frozenLockfile = false

[install.lockfile]
save = true
print = "yarn"


[run]
# default outside of Windows
shell = "system"
# equivalent to `bun --bun` for all `bun run` commands
bun = true