listen-address  127.0.0.1:8118

debug 1
debug 2
debug     4 # show I/O status

enable-proxy-authentication-forwarding 1

forward .wtfismyip.com 127.0.0.1:9080
forward .myip.wtf 127.0.0.1:9080
forward .icanhazip.com 127.0.0.1:9080
forward .checkip.amazonaws.com 127.0.0.1:9080
forward .ipify.org 127.0.0.1:9080
forward .ident.me 127.0.0.1:9080
forward .ifconfig.me 127.0.0.1:9080
forward .my-ip.io 127.0.0.1:9080
forward .whatismyip.akamai.com 127.0.0.1:9080
forward .check.torproject.org 127.0.0.1:9080
forward .freebitco.in 127.0.0.1:9080

forward .cloudflare.com .
