listen-address  127.0.0.1:8118

debug 1
debug 2
debug     4 # show I/O status



# debug 512 # Увімкнення журналу пам’яті
# debug 1024 # Увімкнення журналу клієнтів
# debug 4096 # Увімкнення журналу підключень

enable-proxy-authentication-forwarding 1
max-client-connections 256
socket-timeout 300
accept-intercepted-requests 1

forward .ipaddress.sh 127.0.0.1:9080
forward .httpbin.org 127.0.0.1:9081
forward .ifconfig.io 127.0.0.1:9082
forward .ifconfig.es 127.0.0.1:9083
forward .echoip.de 127.0.0.1:9084
forward .l2.io 127.0.0.1:9085
forward .wtfismyip.com 127.0.0.1:9086
forward .myip.wtf 127.0.0.1:9087
forward .checkip.amazonaws.com 127.0.0.1:9088
forward .ipify.org 127.0.0.1:9089
forward .ident.me 127.0.0.1:9080
forward .ifconfig.pro 127.0.0.1:9081
forward .ipaddy.net 127.0.0.1:9082
forward .ipaddr.site 127.0.0.1:9083
forward .curlmyip.net 127.0.0.1:9084
forward .ifconfig.me 127.0.0.1:9085
forward .my-ip.io 127.0.0.1:9086
forward .whatismyip.akamai.com 127.0.0.1:9087
forward .check.torproject.org 127.0.0.1:9088

forward .google-analytics.com 127.0.0.1:9089
forward .googletagmanager.com 127.0.0.1:9089
forward .hcaptcha.com 127.0.0.1:9089
forward .freebitco.in 127.0.0.1:9089
forward .pushpad.xyz.in 127.0.0.1:9089
forward .forgot-password.sd.workers.dev 127.0.0.1:9089
forward .gstatic.com 127.0.0.1:9089
forward .chart.googleapis.com 127.0.0.1:9089
forward .awstrack.me 127.0.0.1:9089

forward .cloudflare.com .
forward .jsdelivr.net .
